name: ğŸ•ä¸œxlcä»»åŠ¡.

on:
    workflow_dispatch:
    schedule:
        - cron: "5 */3 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: ğŸ•ä¸œxlcä»»åŠ¡.

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•ä¸œå†œåœºã€‘'
              run: |
               node xlcsecret.js
              env:
               JD_COOKIE: ${{ secrets.JD_COOKIE }}
               SYNCURL: https://raw.githubusercontent.com/justnew139/full/main/jd_ddnc.js
               
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•ç§è±†ã€‘'
              run: |
               node xlcsecret.js
              env:
               JD_COOKIE: ${{ secrets.JD_COOKIE }}
               SYNCURL: https://raw.githubusercontent.com/justnew139/full/main/jd_zd.js
            
            
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•ä¸œèŒå® ã€‘'
              run: |
                node xlcsecret.js
              env:
               JD_COOKIE: ${{ secrets.JD_COOKIE }}
               SYNCURL: https://raw.githubusercontent.com/justnew139/full/main/jd_mc.js
            
            
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•ä¸œå†œå‚ã€‘'
              run: |
                node xlcsecret.js
              env:
                 JD_COOKIE: ${{ secrets.JD_COOKIE }}
                 SYNCURL: https://raw.githubusercontent.com/justnew139/full/main/ddnc.js
  
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•å–œå·¥ã€‘'
              run: |
                node xlcsecret.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                SYNCURL: https://raw.githubusercontent.com/justnew139/full/main/jx_gc.js
           
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•ä¸œå¿é‡‘æ´ªåŒ…ã€‘'
              run: |
               node xlcsecret.js
              env:
                 JD_COOKIE: ${{ secrets.JD_COOKIE }}
                 SYNCURL: https://raw.githubusercontent.com/justnew139/full/main/jdhb.js
            
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•ä¸œå–å…³ã€‘'
              run: |
               node xlcsecret.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                SYNCURL: https://raw.githubusercontent.com/justnew139/full/main/jd_unsubscribe.js
            
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•ä¸œTRYã€‘'
              run: |
               node xlcsecret.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                SYNCURL: https://raw.githubusercontent.com/justnew139/full/main/try.js
            
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•ä¸œqianåˆ°ã€‘'
              run: |
               node xlcsecret.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                SYNCURL: https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js
            
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•ä¸œhqiuã€‘'
              run: |
               node xlcsecret.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                SYNCURL: https://raw.githubusercontent.com/justnew139/full/main/jd_huanqiu.js
