name: ğŸ•X

on:
  workflow_dispatch:
  schedule:
    - cron: '36 * * * *'
  watch:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
              npm install
      - name: 'è¿è¡Œ ã€ğŸ•é¹…ã€‘'
        run: |
         node xlcsecret.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: https://raw.githubusercontent.com/justnew139/full/cp-jd/jd_daily_egg.js
            
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'è¿è¡Œ ã€ğŸ•Då·¥ã€‘'
        run: |
          node xlcsecret.js
        env:
           JD_COOKIE: ${{ secrets.JD_COOKIE }}
           SYNCURL: https://raw.githubusercontent.com/justnew139/full/main/jd_ddgc.js
           
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'è¿è¡Œ ã€ğŸ•æ‘‡æ ‘ã€‘'
        run: |
           node xlcsecret.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: https://raw.githubusercontent.com/justnew139/full/cp-jd/jd_moneyTree.js
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: justnew139/youth
          ref: 'main'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: 'ğŸ•Fd'
        run: |
          node cfd.js
        env:
              JD_COOKIE: ${{ secrets.JD_COOKIE }}
              JXNCTOKENS: ${{ secrets.JXNCTOKENS }}
