name: ğŸ•X

on:
  workflow_dispatch:
  schedule:
    - cron: '36 * * * *'
  watch:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
              npm install
      - name: 'è¿è¡Œ ã€ğŸ•é¹…ã€‘'
        run: |
         node xlcsecret.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: https://raw.githubusercontent.com/justnew139/full/cp-jd/jd_daily_egg.js
            
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'è¿è¡Œ ã€ğŸ•Då·¥ã€‘'
        run: |
          node xlcsecret.js
        env:
           JD_COOKIE: ${{ secrets.JD_COOKIE }}
           SYNCURL: https://raw.githubusercontent.com/justnew139/full/main/jd_ddgc.js
           
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'è¿è¡Œ ã€ğŸ•æ‘‡æ ‘ã€‘'
        run: |
           node xlcsecret.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: https://raw.githubusercontent.com/justnew139/full/cp-jd/jd_moneyTree.js
    
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'è¿è¡Œ ã€ğŸ•Fdã€‘'
        run: |
           node xlcsecret.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: https://raw.githubusercontent.com/justnew139/full/main/jx_cfd.js
